version: "3"

services:
  db:
    image: postgres
    container_name: nest_db
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  test-db:
    image: postgres
    container_name: nest_test_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password